# Generated by Django 4.2.30 on 2026-04-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FonepayMerchantCBS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(max_length=50, unique=True)),
                ('merchant_name', models.CharField(blank=True, max_length=200)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('municipality', models.CharField(blank=True, max_length=100)),
                ('address1', models.CharField(blank=True, max_length=300)),
                ('address3', models.CharField(blank=True, max_length=300)),
                ('gender', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Fonepay Merchant CBS',
            },
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('month_name', models.CharField(default='Ashwin', max_length=50)),
                ('fonepay_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('nepalpay_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('fonepay_processed', models.FileField(blank=True, null=True, upload_to='processed/')),
                ('nepalpay_processed', models.FileField(blank=True, null=True, upload_to='processed/')),
                ('final_report', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processed', 'Processed'), ('reviewed', 'Reviewed'), ('final', 'Final Report Generated')], default='uploaded', max_length=20)),
                ('fonepay_row_count', models.IntegerField(default=0)),
                ('nepalpay_row_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NepalpayMerchantCBS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_code', models.CharField(max_length=50)),
                ('merchant_account', models.CharField(blank=True, max_length=50, null=True)),
                ('merchant_name', models.CharField(blank=True, max_length=200)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('municipality', models.CharField(blank=True, max_length=100)),
                ('address1', models.CharField(blank=True, max_length=300)),
                ('address3', models.CharField(blank=True, max_length=300)),
                ('gender', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Nepalpay Merchant CBS',
                'unique_together': {('merchant_code', 'merchant_account')},
            },
        ),
    ]
